version: '3.7'

services:
  record:
    image: ghcr.io/jim60105/docker-twitcasting-recorder
    # build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ${ARCHIVE}:/download
    command: ${TWITCASTING_ID}
    # logging:
    #   driver: "gelf"
    #   options:
    #     gelf-address: "udp://127.0.0.1:12201"
